import { useEffect, useState } from "react"
import { KeyboardArrowRightIcon } from "../ui/icons"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Switch } from "@/components/ui/switch"
import { Separator } from "@/components/ui/separator"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { getSync, setSync } from "@/lib/chrome-storage"
import { useDebouncedEffect } from "@/hooks/use-debounced-effect"
import { cn } from "@/lib/utils"
import MasterDetailLayout from "../components/MasterDetailLayout"
import MobileBackButton from "../components/MobileBackButton"
// Framework-free logic module, imported directly — never duplicated into src/. See
// PLAN.md §6 Phase 5 "Structural rule to preserve". Only used here as the initial/reset
// value for the system-prompt field below — extension/obsidian/store.js's
// getObsidianSettings() is the one place that actually falls back to it at read time.
import { INTERPRETER_SYSTEM_PROMPT } from "../../../extension/obsidian/interpreter.js"

const DEFAULT_LLM_TIMEOUT_MS = 300000

type SettingsCategory = "capture" | "ai" | "about"

const CATEGORIES: { id: SettingsCategory; label: string; description: string }[] = [
    { id: "capture", label: "Capture mode", description: "How TranscripTonic decides when to start capturing a transcript." },
    { id: "ai", label: "AI summary", description: "Enrich the note handed off to Obsidian with a summary generated by an LLM." },
    { id: "about", label: "About", description: "Version and links." },
]

// List (content) + detail panel, same shape as every other page (see
// MasterDetailLayout.tsx) — modeled on x.com/settings/account. Each column owns its own
// title (this page's "Settings" heading vs. whichever category is selected) and scrolls
// independently on `md+`.
export default function SettingsView() {
    const [activeCategory, setActiveCategory] = useState<SettingsCategory>("capture")
    const [mobileDetailOpen, setMobileDetailOpen] = useState(false)
    const [version, setVersion] = useState("")
    const [operationMode, setOperationMode] = useState<"auto" | "manual">("auto")
    const [hideCaptions, setHideCaptions] = useState(false)
    const [llmEnabled, setLlmEnabled] = useState(false)
    const [llmAutoRun, setLlmAutoRun] = useState(true)
    const [llmTimeoutMs, setLlmTimeoutMs] = useState(String(DEFAULT_LLM_TIMEOUT_MS))
    const [llmSystemPrompt, setLlmSystemPrompt] = useState(INTERPRETER_SYSTEM_PROMPT)

    useEffect(() => {
        setVersion(chrome.runtime.getManifest().version)
        getSync<ResultSync>([
            "operationMode",
            "hideCaptions",
            "obsidianUseLlm",
            "obsidianLlmAutoRun",
            "obsidianLlmTimeoutMs",
            "obsidianLlmSystemPrompt",
        ]).then((result) => {
            setOperationMode(result.operationMode === "manual" ? "manual" : "auto")
            setHideCaptions(result.hideCaptions === true)
            setLlmEnabled(result.obsidianUseLlm === true)
            setLlmAutoRun(result.obsidianLlmAutoRun !== false)
            setLlmTimeoutMs(String(result.obsidianLlmTimeoutMs || DEFAULT_LLM_TIMEOUT_MS))
            setLlmSystemPrompt(result.obsidianLlmSystemPrompt || INTERPRETER_SYSTEM_PROMPT)
        })
    }, [])

    function handleOperationModeChange(value: string) {
        const mode = value === "manual" ? "manual" : "auto"
        setOperationMode(mode)
        setSync({ operationMode: mode })
    }

    function handleHideCaptionsChange(checked: boolean) {
        setHideCaptions(checked)
        setSync({ hideCaptions: checked })
    }

    function handleLlmEnabledChange(checked: boolean) {
        setLlmEnabled(checked)
        setSync({ obsidianUseLlm: checked })
    }

    function handleLlmAutoRunChange(checked: boolean) {
        setLlmAutoRun(checked)
        setSync({ obsidianLlmAutoRun: checked })
    }

    useDebouncedEffect(
        () => {
            const parsedTimeout = parseInt(llmTimeoutMs, 10)
            setSync({
                obsidianLlmTimeoutMs: Number.isFinite(parsedTimeout) && parsedTimeout > 0 ? parsedTimeout : DEFAULT_LLM_TIMEOUT_MS,
            })
        },
        [llmTimeoutMs],
        700,
    )

    useDebouncedEffect(
        () => {
            setSync({ obsidianLlmSystemPrompt: llmSystemPrompt.trim() || INTERPRETER_SYSTEM_PROMPT })
        },
        [llmSystemPrompt],
        700,
    )

    function handleResetSystemPrompt() {
        setLlmSystemPrompt(INTERPRETER_SYSTEM_PROMPT)
    }

    const activeCategoryInfo = CATEGORIES.find((c) => c.id === activeCategory) ?? CATEGORIES[0]

    return (
        <MasterDetailLayout
            className="meetings-redesign"
            contentTitle={<h1 className="font-meetings-heading flex-1 text-xl text-black/87">settings</h1>}
            content={
                <div className="flex flex-col">
                    <p className="px-4 pt-4 pb-2 text-sm text-black/60">Capture behavior and app information.</p>
                    {CATEGORIES.map((category) => (
                        <button
                            key={category.id}
                            type="button"
                            className={cn(
                                "flex h-16 items-center justify-between gap-2 px-4 text-left text-sm font-medium text-black/87",
                                activeCategory === category.id && "bg-black/8",
                            )}
                            onClick={() => {
                                setActiveCategory(category.id)
                                setMobileDetailOpen(true)
                            }}
                        >
                            {category.label}
                            <KeyboardArrowRightIcon className="size-4 shrink-0 text-black/38" />
                        </button>
                    ))}
                </div>
            }
            detailTitle={
                <>
                    <MobileBackButton onClick={() => setMobileDetailOpen(false)} />
                    <h2 className="font-meetings-heading text-xl text-black/87">{activeCategoryInfo.label}</h2>
                </>
            }
            detail={
                <div className="px-4">
                    <p className="pt-4 pb-2 text-sm text-black/60">{activeCategoryInfo.description}</p>
                    {activeCategory === "capture" ? (
                        <div>
                            <RadioGroup value={operationMode} onValueChange={handleOperationModeChange} className="gap-3">
                                <div className="flex items-start gap-2">
                                    <RadioGroupItem value="auto" id="auto-mode" className="mt-0.5" />
                                    <Label htmlFor="auto-mode" className="flex-col items-start font-normal">
                                        <span className="font-bold text-black/87">Auto mode</span>
                                        <span className="text-black/60">Get transcripts of all meetings</span>
                                    </Label>
                                </div>
                                <div className="flex items-start gap-2">
                                    <RadioGroupItem value="manual" id="manual-mode" className="mt-0.5" />
                                    <Label htmlFor="manual-mode" className="flex-col items-start font-normal">
                                        <span className="font-bold text-black/87">Manual mode</span>
                                        <span className="text-black/60">
                                            Switch on transcript when needed during the meeting
                                        </span>
                                    </Label>
                                </div>
                            </RadioGroup>

                            <Separator className="my-4" />

                            <div className="flex items-center gap-2">
                                <Checkbox
                                    id="hide-captions"
                                    checked={hideCaptions}
                                    onCheckedChange={(v) => handleHideCaptionsChange(v === true)}
                                />
                                <Label htmlFor="hide-captions" className="font-bold text-black/87">
                                    Hide captions on the meeting UI
                                </Label>
                            </div>
                        </div>
                    ) : activeCategory === "ai" ? (
                        <div>
                            <div className="flex items-start justify-between gap-4">
                                <div>
                                    <p className="font-bold text-black/87">Enable LLM summary</p>
                                    <p className="mt-1 text-sm text-black/60">
                                        Configure a provider and pick a model on the Integrations page.
                                    </p>
                                </div>
                                <Switch checked={llmEnabled} onCheckedChange={handleLlmEnabledChange} />
                            </div>

                            <Separator className="my-4" />

                            <div className={`flex items-start justify-between gap-4 ${llmEnabled ? "" : "opacity-50"}`}>
                                <div>
                                    <p className="font-bold text-black/87">Automatically run</p>
                                    <p className="mt-1 text-sm text-black/60">
                                        Summarize automatically whenever a meeting is saved to Obsidian. Turn off to
                                        only summarize on demand — a "Summarize now" action stays available in each
                                        meeting's menu on the Meetings page either way.
                                    </p>
                                </div>
                                <Switch checked={llmAutoRun} disabled={!llmEnabled} onCheckedChange={handleLlmAutoRunChange} />
                            </div>

                            <Separator className="my-4" />

                            <div className={llmEnabled ? "" : "opacity-50"}>
                                <Label htmlFor="obsidian-llm-timeout">Timeout (milliseconds)</Label>
                                <Input
                                    type="number"
                                    id="obsidian-llm-timeout"
                                    className="mt-2 rounded-none"
                                    min={1000}
                                    step={1000}
                                    placeholder="300000"
                                    value={llmTimeoutMs}
                                    disabled={!llmEnabled}
                                    onChange={(e) => setLlmTimeoutMs(e.target.value)}
                                />
                                <p className="mt-1 text-xs text-black/60">
                                    How long to wait before giving up and saving the plain transcript instead.
                                    Default is 300000 (5 minutes) — models can be slow, especially on long
                                    transcripts.
                                </p>
                            </div>

                            <Separator className="my-4" />

                            <div className={llmEnabled ? "" : "opacity-50"}>
                                <div className="flex items-center justify-between gap-4">
                                    <Label htmlFor="obsidian-llm-system-prompt">System prompt</Label>
                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="sm"
                                        className="rounded-none"
                                        disabled={!llmEnabled}
                                        onClick={handleResetSystemPrompt}
                                    >
                                        Reset to default
                                    </Button>
                                </div>
                                <Textarea
                                    id="obsidian-llm-system-prompt"
                                    className="mt-2 min-h-48 rounded-none font-mono text-xs"
                                    value={llmSystemPrompt}
                                    disabled={!llmEnabled}
                                    onChange={(e) => setLlmSystemPrompt(e.target.value)}
                                />
                                <p className="text-black/60 mt-1 text-xs">
                                    The full instruction sent to the model before every summarization request.
                                    Editing out the "respond with a single JSON object" instruction will break
                                    summarization — use Reset to default if that happens.
                                </p>
                            </div>
                        </div>
                    ) : (
                        <p className="text-black/60 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm">
                            <span>v{version}</span>
                            <span>·</span>
                            <a
                                className="font-bold text-black/87 underline underline-offset-4"
                                href="https://github.com/vivek-nexus/transcriptonic?tab=readme-ov-file#notice"
                                target="_blank"
                                rel="noreferrer"
                            >
                                Notice
                            </a>
                            <span>·</span>
                            <a
                                className="font-bold text-black/87 underline underline-offset-4"
                                href="https://github.com/vivek-nexus/transcriptonic#readme"
                                target="_blank"
                                rel="noreferrer"
                            >
                                Get help
                            </a>
                            <span>·</span>
                            <a
                                className="font-bold text-black/87 underline underline-offset-4"
                                href="https://github.com/vivek-nexus/transcriptonic/issues"
                                target="_blank"
                                rel="noreferrer"
                            >
                                Report a bug
                            </a>
                            <span>·</span>
                            <span>
                                Another project by{" "}
                                <a
                                    className="font-bold text-black/87 underline underline-offset-4"
                                    href="https://vivek-nexus.github.io"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    Vivek
                                </a>
                            </span>
                        </p>
                    )}
                </div>
            }
            mobileDetailOpen={mobileDetailOpen}
        />
    )
}
